name: Python CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install from pyproject.toml if it exists
        if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
        # Install development tools
        pip install flake8 black mypy pytest pytest-cov bandit safety
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv,env,.venv,.env
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv,env,.venv,.env
      continue-on-error: true
    
    - name: Check code formatting with black
      run: |
        black --check --diff . --exclude='/(venv|env|\.venv|\.env)/'
      continue-on-error: true
    
    - name: Type checking with mypy
      run: |
        mypy . --ignore-missing-imports --no-strict-optional --exclude='(venv|env|\.venv|\.env)'
      continue-on-error: true
    
    - name: Run tests with pytest
      run: |
        pytest tests/ -v --cov=. --cov-report=xml --cov-report=term-missing
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
      continue-on-error: true
      if: matrix.python-version == '3.11'
    
    - name: Security check with bandit
      run: |
        bandit -r . -f json -o bandit-report.json --exclude './venv,./env,./.venv,./.env' || true
        bandit -r . -f screen --exclude './venv,./env,./.venv,./.env'
      continue-on-error: true
    
    - name: Check dependencies for vulnerabilities
      run: |
        safety check --json || true
      continue-on-error: true

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install -e .; fi
    
    - name: Verify application structure
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        echo "Application structure verified"
    
    - name: Check for required files
      run: |
        test -f README.md && echo "✓ README.md found" || echo "⚠ README.md missing"
        test -f LICENSE && echo "✓ LICENSE found" || echo "⚠ LICENSE missing"
        test -f .gitignore && echo "✓ .gitignore found" || echo "⚠ .gitignore missing"

